Feat/board
spartaSpringTeamA6/dev-quiz-backend pull request #35
Opened 2024-01-15 07:01 UTC by Youkamii

살살때려주세요..

2024-01-15 07:09 UTC, dmlal commented on src/main/java/com/sparta/devquiz/domain/board/controller/BoardController.java
> +    @GetMapping("/api/boards/{board_id}")
이러면 동작이 되지않습니다 선생님..  /api 를 빼셔야합니다.

2024-01-15 07:15 UTC, dmlal commented on src/main/java/com/sparta/devquiz/domain/board/dto/RequestDto/BoardUpdateRequestDto.java
> +}
**P4**  생성자 생성에 관해 통일을 하시면 좋을것 같아요

2024-01-15 07:19 UTC, dmlal commented on src/main/java/com/sparta/devquiz/domain/board/service/BoardService.java
> +    @Transactional
**P5**:  트랜잭션을 Create에 거신 이유가 있나요

2024-01-15 07:21 UTC, dmlal commented on src/main/java/com/sparta/devquiz/domain/board/service/BoardService.java
> +                .orElseThrow(() -> new CustomException(HttpStatus.NO_CONTENT, "404", "Board not found"));
**P1**:  throw new CoinCustomException(CoinExceptionCode.BAD_REQUEST_COIN);  이런식으로 통일해주시면 좋을것같은데  컨벤션이 변경된다면 그에 맞춰 해주시면 좋을것같아요

2024-01-15 07:23 UTC, dmlal commented on src/main/java/com/sparta/devquiz/domain/board/service/BoardService.java
> +                .collect(Collectors.toList());
**P3**:  collect 이부분은 toList로 바꿀수있는것으로 알고있습니다.

2024-01-15 07:24 UTC, dmlal commented on src/main/java/com/sparta/devquiz/domain/board/service/BoardService.java
> +                .orElseThrow(() -> new CustomException(HttpStatus.NOT_FOUND, "404", "Board not found"));
**P1**:  3개째 당첨입니다.  메소드로 빼주세요

2024-01-15 07:25 UTC, dmlal requested changes
코멘트 단 부분과

Dto 네이밍에서  dto를 빼주셔야합니다.

2024-01-15 07:30 UTC, jiisuniui commented on src/main/java/com/sparta/devquiz/domain/board/dto/RequestDto/BoardRequestDto.java
> +public class BoardRequestDto {
**P1**: 컨벤션에 "Domain+동작+응답/요청" 으로 네이밍하기로 해서 
- BoardCreateRequest
- BoardSaveRequest
같은걸로 바꿔주시면 될 것 같습니다

2024-01-15 07:31 UTC, jiisuniui approved these changes

2024-01-15 07:31 UTC, jiisuniui commented on src/main/java/com/sparta/devquiz/domain/board/dto/RequestDto/BoardUpdateRequestDto.java
> +}
**P4**: request는 getter만 쓰면 될 것 같습니다

2024-01-15 07:32 UTC, jiisuniui commented on src/main/java/com/sparta/devquiz/domain/board/dto/ResponseDto/BoardCreateResponseDto.java
> +}
**P5**: setter 사용 지양해주시면 감사하겠습니다! example 코드에 of 사용 권장드립니다

2024-01-15 07:37 UTC, rawfk commented on src/main/java/com/sparta/devquiz/domain/board/controller/BoardController.java
> +                new CommonResponseDto<>(
**P1** :  반환 형식을 아래와 같이 status().body의 형식으로 통일해주세요. 
그리고, Status도 CustomCode의 Status를 사용해주세요.
return ResponseEntity.status(UserResponseCode.GET_MY_INFO.getHttpStatus())
        .body(CommonResponseDto.of(UserResponseCode.GET_MY_INFO, result));

2024-01-15 07:37 UTC, rawfk commented on src/main/java/com/sparta/devquiz/domain/board/controller/BoardController.java
> +                        null
**P1** :  데이터가 없는 경우 null을 넣지않고 CommonResponseDto.of(ResponseCode)의 메서드를 사용해주세요

2024-01-16 07:35 UTC, jiisuniui commented on src/main/java/com/sparta/devquiz/domain/board/dto/request/BoardRequest.java
> +public class BoardRequest {
@Schema(description = "보드 생성 요청 dto") 요러케 붙여주세요

2024-01-16 07:35 UTC, jiisuniui commented on src/main/java/com/sparta/devquiz/domain/board/dto/request/BoardRequest.java
> +public class BoardRequest {
request, response 다 붙여주세요

2024-01-16 07:37 UTC, jiisuniui commented on src/main/java/com/sparta/devquiz/domain/board/controller/BoardController.java
> +            @Valid @RequestBody BoardUpdateRequest boardUpdateRequestDto,
P1: 요거 dto 두개 걸린것같은데요...?

2024-01-16 07:39 UTC, jiisuniui commented on src/main/java/com/sparta/devquiz/domain/board/controller/BoardController.java
> +    @Operation(summary = "Board 수정")
P2: operationId = "Board-004"같이 붙여주세욤

2024-01-16 07:39 UTC, jiisuniui commented on src/main/java/com/sparta/devquiz/domain/board/controller/BoardController.java
> +            @Valid @RequestBody BoardUpdateRequest boardUpdateRequestDto,
혹싀... 실행됐나요 이거?

2024-01-16 07:39 UTC, jiisuniui commented on src/main/java/com/sparta/devquiz/domain/board/controller/BoardController.java
> +                .status(BoardResponseCode.NO_CONTENT_UPDATE_BOARD.getHttpStatus())
P1: 저희 NO_CONTENT 말고 OK 쓰기로 했었습니당!

2024-01-16 07:40 UTC, jiisuniui commented on src/main/java/com/sparta/devquiz/domain/board/controller/BoardController.java
> +    @Operation(summary = "Board 삭제")
P2: operationId = "Board-005"같이 API-CODE 붙여주세욤

2024-01-16 08:01 UTC, jiisuniui requested changes

2024-01-16 08:01 UTC, jiisuniui commented on src/main/java/com/sparta/devquiz/domain/board/controller/BoardController.java
> +                .body(CommonResponseDto.of(BoardResponseCode.NO_CONTENT_UPDATE_BOARD));
P1: 저희 NO_CONTENT 말고 OK 쓰기로 했었습니당!

2024-01-16 08:01 UTC, jiisuniui commented on src/main/java/com/sparta/devquiz/domain/board/controller/BoardController.java
> +                .body(CommonResponseDto.of(BoardResponseCode.NO_CONTENT_DELETE_BOARD));
P1: 여기도 NO_CONTENT 말고 OK 로 바꿔주세욤

2024-01-16 08:01 UTC, jiisuniui commented on src/main/java/com/sparta/devquiz/domain/board/controller/BoardController.java
> +
P5: 공백이욤 허허

2024-01-16 08:01 UTC, jiisuniui commented on src/main/java/com/sparta/devquiz/domain/board/dto/request/BoardUpdateRequest.java
> +@NoArgsConstructor
P2: NoArgs request에 쓸 일 없을 것 같은데 맞나요?

2024-01-16 08:01 UTC, jiisuniui commented on src/main/java/com/sparta/devquiz/domain/board/dto/response/BoardDetailsResponse.java
> +@Schema(description = "보드 정보 응답 Dto")
P5: dto로... 바꿔주실수... 아닙니다

2024-01-16 08:01 UTC, jiisuniui commented on src/main/java/com/sparta/devquiz/domain/board/dto/response/BoardSingleGetResponse.java
> +}
P1: 요기 of 만들고, builder 붙이고 allargs 하면 좋을 것 같습니당

2024-01-16 08:01 UTC, jiisuniui commented on src/main/java/com/sparta/devquiz/domain/board/repository/BoardRepository.java
> +        List<Board> findAllByQuizId(Long quizId);
P1: 요거 isDeleted false 안해도 되나요??

2024-01-16 08:01 UTC, jiisuniui commented on src/main/java/com/sparta/devquiz/domain/board/response/BoardResponseCode.java
P1: NO_CONTENT 부분 OK쪽으로 가면 좋을 것 같습니당

2024-01-16 08:01 UTC, jiisuniui commented on src/main/java/com/sparta/devquiz/domain/board/response/BoardResponseCode.java
P1: 요거 붙여주세요! 그리고 HttpStatus.OK.value()요거에서 value 빼주세요!

    // OK 200
    OK_GET_BOARDLIST_INFO(HttpStatus.OK, "SUCCESS TO GET BOARDLIST"),
    OK_GET_BOARD_INFO(HttpStatus.OK, "SUCCESS TO GET BOARD"),
    OK_UPDATE_BOARD(HttpStatus.OK, "SUCCESS TO UPDATE BOARD"),
    OK_DELETE_BOARD(HttpStatus.OK, "SUCCESS TO DELETE BOARD"),

    // CREATED 201
    CREATED_BOARD(HttpStatus.CREATED, "SUCCESS TO CREATE BOARD");

    // NO CONTENT 204
    
    private final HttpStatus httpStatus;
    private final String message;

    public HttpStatus getHttpStatus(TeamResponseCode responseCode){
        return responseCode.getHttpStatus();
    }

    public String getMessage(TeamResponseCode responseCode){
        return responseCode.getMessage();
    }

2024-01-16 08:01 UTC, jiisuniui commented on src/main/java/com/sparta/devquiz/domain/board/service/BoardService.java
> +                .orElseThrow(() -> new BoardCustomException(BoardExceptionCode.NOT_FOUND_QUIZ));
P1: quiz api에서 service에서 메소드 만들어서 가져와서 사용해야 될 것 같습니다~! 원활한 합의..!

2024-01-16 08:01 UTC, jiisuniui commented on src/main/java/com/sparta/devquiz/domain/board/service/BoardService.java
> +                .orElseThrow(() -> new BoardCustomException(BoardExceptionCode.NOT_FOUND_BOARD));
P2: 요거 중복코드라 메소드로 따로 빼주세욤

2024-01-16 08:01 UTC, jiisuniui commented on src/main/java/com/sparta/devquiz/domain/board/service/BoardService.java
> +
P2: 요것도 메소드로 빼면 좋을 것 같습니당

2024-01-16 08:13 UTC, Youkamii commented on src/main/java/com/sparta/devquiz/domain/board/controller/BoardController.java
> +            @Valid @RequestBody BoardUpdateRequest boardUpdateRequestDto,
아 이것도 아직 수정중잉ㅂ니다 ㅋㅋㅋ
이상하게 했다고 했는데 눈에 걸리는것들이 계속 보여서 push 안된 부분이 좀 더 있습니다

2024-01-17 01:25 UTC, rawfk requested changes

2024-01-17 01:25 UTC, rawfk commented on src/main/java/com/sparta/devquiz/domain/board/response/BoardResponseCode.java
> +    OK_DELETE_BOARD(HttpStatus.NO_CONTENT, "SUCCESS TO DELETE BOARD");
**P1**: Status No_CONTENT -> OK로 변경해주세요.

2024-01-17 01:25 UTC, rawfk commented on src/main/java/com/sparta/devquiz/domain/board/service/BoardService.java
> +        boardRepository.save(board);
**P1**: save()가 불필요합니다.

2024-01-17 01:25 UTC, rawfk commented on src/main/java/com/sparta/devquiz/domain/board/service/BoardService.java
> +        boardRepository.save(board);
**P1**: save()가 불필요합니다.

2024-01-17 01:25 UTC, rawfk commented on src/main/java/com/sparta/devquiz/domain/comment/controller/CommentController.java
> +    @DeleteMapping("/comments/{comment_id}")
**P1**: PathVariable snake case에서 camel case로 변경해주세요.

2024-01-17 01:25 UTC, rawfk commented on src/main/java/com/sparta/devquiz/domain/comment/controller/CommentController.java
> +    @PostMapping("/comments/{comment_id}/like")
**P1**: PathVariable snake case에서 camel case로 변경해주세요.

2024-01-17 01:25 UTC, rawfk commented on src/main/java/com/sparta/devquiz/domain/comment/controller/CommentController.java
> +    @DeleteMapping("/comments/{comment_id}/unlike")
**P1**: PathVariable snake case에서 camel case로 변경해주세요.

2024-01-17 01:25 UTC, rawfk commented on src/main/java/com/sparta/devquiz/domain/comment/response/CommentResponseCode.java
> +    OK_DELETE_LIKE(HttpStatus.NO_CONTENT, "SUCCESS TO DELETE LIKE");
P1: Status No_CONTENT -> OK로 변경해주세요.

2024-01-17 09:26 UTC, dmlal commented on src/main/java/com/sparta/devquiz/domain/board/response/BoardResponseCode.java
> +    // OK 204:  기존 RESPONSE CODE 200에서 DATA가 "" 인 것들을 204로 사용
나중에 200으로 옮기시면 될 것 같습니다.

2024-01-17 09:51 UTC, dmlal approved these changes

2024-01-17 09:52 UTC, merged